// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.7.1
// source: privacy.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	types "github.com/qlcchain/go-qlc/rpc/grpc/proto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PrivacyDistributeParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawPayload     []byte   `protobuf:"bytes,1,opt,name=rawPayload,proto3" json:"rawPayload,omitempty"`
	PrivateFrom    string   `protobuf:"bytes,2,opt,name=privateFrom,proto3" json:"privateFrom,omitempty"`
	PrivateFor     []string `protobuf:"bytes,3,rep,name=privateFor,proto3" json:"privateFor,omitempty"`
	PrivateGroupID string   `protobuf:"bytes,4,opt,name=privateGroupID,proto3" json:"privateGroupID,omitempty"`
}

func (x *PrivacyDistributeParam) Reset() {
	*x = PrivacyDistributeParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privacy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivacyDistributeParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacyDistributeParam) ProtoMessage() {}

func (x *PrivacyDistributeParam) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivacyDistributeParam.ProtoReflect.Descriptor instead.
func (*PrivacyDistributeParam) Descriptor() ([]byte, []int) {
	return file_privacy_proto_rawDescGZIP(), []int{0}
}

func (x *PrivacyDistributeParam) GetRawPayload() []byte {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

func (x *PrivacyDistributeParam) GetPrivateFrom() string {
	if x != nil {
		return x.PrivateFrom
	}
	return ""
}

func (x *PrivacyDistributeParam) GetPrivateFor() []string {
	if x != nil {
		return x.PrivateFor
	}
	return nil
}

func (x *PrivacyDistributeParam) GetPrivateGroupID() string {
	if x != nil {
		return x.PrivateGroupID
	}
	return ""
}

var File_privacy_proto protoreflect.FileDescriptor

var file_privacy_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x63, 0x79, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x61, 0x77, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x46,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x46, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x32, 0xce, 0x03, 0x0a,
	0x0a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x41, 0x50, 0x49, 0x12, 0x7c, 0x0a, 0x14, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x61, 0x77, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x63, 0x79, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x1a, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x22, 0x1d, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63,
	0x79, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x61, 0x77, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x3a, 0x01, 0x2a, 0x12, 0x6c, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x52, 0x61, 0x77, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16, 0x2f, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2f, 0x67, 0x65, 0x74, 0x52, 0x61, 0x77, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x3a, 0x01, 0x2a, 0x12, 0x6e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x0b, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x1b,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2a, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x24, 0x22, 0x1f, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2f, 0x67, 0x65,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x3a, 0x01, 0x2a, 0x12, 0x64, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x6d, 0x6f, 0x4b, 0x56, 0x12, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1d,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x12, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79,
	0x2f, 0x67, 0x65, 0x74, 0x44, 0x65, 0x6d, 0x6f, 0x4b, 0x56, 0x3a, 0x01, 0x2a, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_privacy_proto_rawDescOnce sync.Once
	file_privacy_proto_rawDescData = file_privacy_proto_rawDesc
)

func file_privacy_proto_rawDescGZIP() []byte {
	file_privacy_proto_rawDescOnce.Do(func() {
		file_privacy_proto_rawDescData = protoimpl.X.CompressGZIP(file_privacy_proto_rawDescData)
	})
	return file_privacy_proto_rawDescData
}

var file_privacy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_privacy_proto_goTypes = []interface{}{
	(*PrivacyDistributeParam)(nil), // 0: proto.PrivacyDistributeParam
	(*wrappers.BytesValue)(nil),    // 1: google.protobuf.BytesValue
	(*types.Hash)(nil),             // 2: types.Hash
}
var file_privacy_proto_depIdxs = []int32{
	0, // 0: proto.PrivacyAPI.DistributeRawPayload:input_type -> proto.PrivacyDistributeParam
	1, // 1: proto.PrivacyAPI.GetRawPayload:input_type -> google.protobuf.BytesValue
	2, // 2: proto.PrivacyAPI.GetBlockPrivatePayload:input_type -> types.Hash
	1, // 3: proto.PrivacyAPI.GetDemoKV:input_type -> google.protobuf.BytesValue
	1, // 4: proto.PrivacyAPI.DistributeRawPayload:output_type -> google.protobuf.BytesValue
	1, // 5: proto.PrivacyAPI.GetRawPayload:output_type -> google.protobuf.BytesValue
	1, // 6: proto.PrivacyAPI.GetBlockPrivatePayload:output_type -> google.protobuf.BytesValue
	1, // 7: proto.PrivacyAPI.GetDemoKV:output_type -> google.protobuf.BytesValue
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_privacy_proto_init() }
func file_privacy_proto_init() {
	if File_privacy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_privacy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivacyDistributeParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_privacy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_privacy_proto_goTypes,
		DependencyIndexes: file_privacy_proto_depIdxs,
		MessageInfos:      file_privacy_proto_msgTypes,
	}.Build()
	File_privacy_proto = out.File
	file_privacy_proto_rawDesc = nil
	file_privacy_proto_goTypes = nil
	file_privacy_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrivacyAPIClient is the client API for PrivacyAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrivacyAPIClient interface {
	DistributeRawPayload(ctx context.Context, in *PrivacyDistributeParam, opts ...grpc.CallOption) (*wrappers.BytesValue, error)
	GetRawPayload(ctx context.Context, in *wrappers.BytesValue, opts ...grpc.CallOption) (*wrappers.BytesValue, error)
	GetBlockPrivatePayload(ctx context.Context, in *types.Hash, opts ...grpc.CallOption) (*wrappers.BytesValue, error)
	GetDemoKV(ctx context.Context, in *wrappers.BytesValue, opts ...grpc.CallOption) (*wrappers.BytesValue, error)
}

type privacyAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivacyAPIClient(cc grpc.ClientConnInterface) PrivacyAPIClient {
	return &privacyAPIClient{cc}
}

func (c *privacyAPIClient) DistributeRawPayload(ctx context.Context, in *PrivacyDistributeParam, opts ...grpc.CallOption) (*wrappers.BytesValue, error) {
	out := new(wrappers.BytesValue)
	err := c.cc.Invoke(ctx, "/proto.PrivacyAPI/DistributeRawPayload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyAPIClient) GetRawPayload(ctx context.Context, in *wrappers.BytesValue, opts ...grpc.CallOption) (*wrappers.BytesValue, error) {
	out := new(wrappers.BytesValue)
	err := c.cc.Invoke(ctx, "/proto.PrivacyAPI/GetRawPayload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyAPIClient) GetBlockPrivatePayload(ctx context.Context, in *types.Hash, opts ...grpc.CallOption) (*wrappers.BytesValue, error) {
	out := new(wrappers.BytesValue)
	err := c.cc.Invoke(ctx, "/proto.PrivacyAPI/GetBlockPrivatePayload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyAPIClient) GetDemoKV(ctx context.Context, in *wrappers.BytesValue, opts ...grpc.CallOption) (*wrappers.BytesValue, error) {
	out := new(wrappers.BytesValue)
	err := c.cc.Invoke(ctx, "/proto.PrivacyAPI/GetDemoKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivacyAPIServer is the server API for PrivacyAPI service.
type PrivacyAPIServer interface {
	DistributeRawPayload(context.Context, *PrivacyDistributeParam) (*wrappers.BytesValue, error)
	GetRawPayload(context.Context, *wrappers.BytesValue) (*wrappers.BytesValue, error)
	GetBlockPrivatePayload(context.Context, *types.Hash) (*wrappers.BytesValue, error)
	GetDemoKV(context.Context, *wrappers.BytesValue) (*wrappers.BytesValue, error)
}

// UnimplementedPrivacyAPIServer can be embedded to have forward compatible implementations.
type UnimplementedPrivacyAPIServer struct {
}

func (*UnimplementedPrivacyAPIServer) DistributeRawPayload(context.Context, *PrivacyDistributeParam) (*wrappers.BytesValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributeRawPayload not implemented")
}
func (*UnimplementedPrivacyAPIServer) GetRawPayload(context.Context, *wrappers.BytesValue) (*wrappers.BytesValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRawPayload not implemented")
}
func (*UnimplementedPrivacyAPIServer) GetBlockPrivatePayload(context.Context, *types.Hash) (*wrappers.BytesValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockPrivatePayload not implemented")
}
func (*UnimplementedPrivacyAPIServer) GetDemoKV(context.Context, *wrappers.BytesValue) (*wrappers.BytesValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDemoKV not implemented")
}

func RegisterPrivacyAPIServer(s *grpc.Server, srv PrivacyAPIServer) {
	s.RegisterService(&_PrivacyAPI_serviceDesc, srv)
}

func _PrivacyAPI_DistributeRawPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivacyDistributeParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyAPIServer).DistributeRawPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PrivacyAPI/DistributeRawPayload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyAPIServer).DistributeRawPayload(ctx, req.(*PrivacyDistributeParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyAPI_GetRawPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.BytesValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyAPIServer).GetRawPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PrivacyAPI/GetRawPayload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyAPIServer).GetRawPayload(ctx, req.(*wrappers.BytesValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyAPI_GetBlockPrivatePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Hash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyAPIServer).GetBlockPrivatePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PrivacyAPI/GetBlockPrivatePayload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyAPIServer).GetBlockPrivatePayload(ctx, req.(*types.Hash))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyAPI_GetDemoKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.BytesValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyAPIServer).GetDemoKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PrivacyAPI/GetDemoKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyAPIServer).GetDemoKV(ctx, req.(*wrappers.BytesValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrivacyAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PrivacyAPI",
	HandlerType: (*PrivacyAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DistributeRawPayload",
			Handler:    _PrivacyAPI_DistributeRawPayload_Handler,
		},
		{
			MethodName: "GetRawPayload",
			Handler:    _PrivacyAPI_GetRawPayload_Handler,
		},
		{
			MethodName: "GetBlockPrivatePayload",
			Handler:    _PrivacyAPI_GetBlockPrivatePayload_Handler,
		},
		{
			MethodName: "GetDemoKV",
			Handler:    _PrivacyAPI_GetDemoKV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "privacy.proto",
}
