# https://docs.codecov.io/docs/codecov-yaml

codecov:
  max_report_age: off

ignore:
- "**/mock"
- "**/edwards25519/*"

#comment: false

coverage:
  range: 40..70
  precision: 2
  round: down
  status:
    project:
      default:
        threshold: 2%
        if_not_found: success
    patch:
      default:
        enabled: yes
        threshold: 0%
        if_not_found: success
    changes:
      default:
        enabled: yes
        if_not_found: success
