# https://docs.codecov.io/docs/codecov-yaml

codecov:
  max_report_age: off

ignore:
- "**/mock"
- "**/edwards25519/*"
- "**/*_gen.go"
- "**/*.pb.go"
- "**/proto/*"
- "cmd/**/*"

#comment: false

coverage:
  range: 50..70
  
