pull_request_rules:
  - name: automatic merge when CI passes and 1 more reviews
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Check, Build and Publish snapshot artifacts
      - label=ready-to-merge
    actions:
      merge:
        method: merge
  - name: automatic squash when CI passes and 1 more reviews
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Check, Build and Publish snapshot artifacts
      - label=ready-to-rebase-and-merge
    actions:
      merge:
        method: squash
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}