language: go

go:
  - 1.x

os:
  - linux

dist: xenial

cache:
   directories:
     - $HOME/gopath/pkg/mod

services:
  - docker

sudo: true

before_install:
  - docker --version
  - go get -u github.com/gythialy/xgo

addons:
  apt:
    update: true
    packages:
      - docker-ce

env:
 global:
   - GO111MODULE=on

script:
  - ./ci/travis.gofmt.sh
  - ./ci/travis.govet.sh
  - ./ci/travis.codecov.sh
  - make clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - | 
    if [[ -n "$TRAVIS_TAG" ]]
    then 
        make clean all
        bash ci/travis.sha256.sh 
    fi

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    file: build/*
    file_glob: true
    skip_cleanup: true
    draft: true
    on:
      tags: true
  - provider: script
    script: ci/deploy-docker.sh
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false
