// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FrontierReq struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Age                  uint32   `protobuf:"varint,2,opt,name=Age,proto3" json:"Age,omitempty"`
	Count                uint32   `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrontierReq) Reset()         { *m = FrontierReq{} }
func (m *FrontierReq) String() string { return proto.CompactTextString(m) }
func (*FrontierReq) ProtoMessage()    {}
func (*FrontierReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *FrontierReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontierReq.Unmarshal(m, b)
}
func (m *FrontierReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontierReq.Marshal(b, m, deterministic)
}
func (dst *FrontierReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontierReq.Merge(dst, src)
}
func (m *FrontierReq) XXX_Size() int {
	return xxx_messageInfo_FrontierReq.Size(m)
}
func (m *FrontierReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontierReq.DiscardUnknown(m)
}

var xxx_messageInfo_FrontierReq proto.InternalMessageInfo

func (m *FrontierReq) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *FrontierReq) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *FrontierReq) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type FrontierRsp struct {
	Frontiers            [][]byte `protobuf:"bytes,1,rep,name=Frontiers,proto3" json:"Frontiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrontierRsp) Reset()         { *m = FrontierRsp{} }
func (m *FrontierRsp) String() string { return proto.CompactTextString(m) }
func (*FrontierRsp) ProtoMessage()    {}
func (*FrontierRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}
func (m *FrontierRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontierRsp.Unmarshal(m, b)
}
func (m *FrontierRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontierRsp.Marshal(b, m, deterministic)
}
func (dst *FrontierRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontierRsp.Merge(dst, src)
}
func (m *FrontierRsp) XXX_Size() int {
	return xxx_messageInfo_FrontierRsp.Size(m)
}
func (m *FrontierRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontierRsp.DiscardUnknown(m)
}

var xxx_messageInfo_FrontierRsp proto.InternalMessageInfo

func (m *FrontierRsp) GetFrontiers() [][]byte {
	if m != nil {
		return m.Frontiers
	}
	return nil
}

type BulkPullReq struct {
	StartHash            []byte   `protobuf:"bytes,1,opt,name=StartHash,proto3" json:"StartHash,omitempty"`
	EndHash              []byte   `protobuf:"bytes,2,opt,name=EndHash,proto3" json:"EndHash,omitempty"`
	PullType             uint32   `protobuf:"varint,3,opt,name=PullType,proto3" json:"PullType,omitempty"`
	Count                uint32   `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	Hashes               []byte   `protobuf:"bytes,5,opt,name=Hashes,proto3" json:"Hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkPullReq) Reset()         { *m = BulkPullReq{} }
func (m *BulkPullReq) String() string { return proto.CompactTextString(m) }
func (*BulkPullReq) ProtoMessage()    {}
func (*BulkPullReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}
func (m *BulkPullReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkPullReq.Unmarshal(m, b)
}
func (m *BulkPullReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkPullReq.Marshal(b, m, deterministic)
}
func (dst *BulkPullReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkPullReq.Merge(dst, src)
}
func (m *BulkPullReq) XXX_Size() int {
	return xxx_messageInfo_BulkPullReq.Size(m)
}
func (m *BulkPullReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkPullReq.DiscardUnknown(m)
}

var xxx_messageInfo_BulkPullReq proto.InternalMessageInfo

func (m *BulkPullReq) GetStartHash() []byte {
	if m != nil {
		return m.StartHash
	}
	return nil
}

func (m *BulkPullReq) GetEndHash() []byte {
	if m != nil {
		return m.EndHash
	}
	return nil
}

func (m *BulkPullReq) GetPullType() uint32 {
	if m != nil {
		return m.PullType
	}
	return 0
}

func (m *BulkPullReq) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *BulkPullReq) GetHashes() []byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type BulkPullRsp struct {
	Blocks               []byte   `protobuf:"bytes,1,opt,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkPullRsp) Reset()         { *m = BulkPullRsp{} }
func (m *BulkPullRsp) String() string { return proto.CompactTextString(m) }
func (*BulkPullRsp) ProtoMessage()    {}
func (*BulkPullRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}
func (m *BulkPullRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkPullRsp.Unmarshal(m, b)
}
func (m *BulkPullRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkPullRsp.Marshal(b, m, deterministic)
}
func (dst *BulkPullRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkPullRsp.Merge(dst, src)
}
func (m *BulkPullRsp) XXX_Size() int {
	return xxx_messageInfo_BulkPullRsp.Size(m)
}
func (m *BulkPullRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkPullRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BulkPullRsp proto.InternalMessageInfo

func (m *BulkPullRsp) GetBlocks() []byte {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type BulkPushBlock struct {
	Blocks               []byte   `protobuf:"bytes,1,opt,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkPushBlock) Reset()         { *m = BulkPushBlock{} }
func (m *BulkPushBlock) String() string { return proto.CompactTextString(m) }
func (*BulkPushBlock) ProtoMessage()    {}
func (*BulkPushBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}
func (m *BulkPushBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkPushBlock.Unmarshal(m, b)
}
func (m *BulkPushBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkPushBlock.Marshal(b, m, deterministic)
}
func (dst *BulkPushBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkPushBlock.Merge(dst, src)
}
func (m *BulkPushBlock) XXX_Size() int {
	return xxx_messageInfo_BulkPushBlock.Size(m)
}
func (m *BulkPushBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkPushBlock.DiscardUnknown(m)
}

var xxx_messageInfo_BulkPushBlock proto.InternalMessageInfo

func (m *BulkPushBlock) GetBlocks() []byte {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type PublishBlock struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishBlock) Reset()         { *m = PublishBlock{} }
func (m *PublishBlock) String() string { return proto.CompactTextString(m) }
func (*PublishBlock) ProtoMessage()    {}
func (*PublishBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}
func (m *PublishBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishBlock.Unmarshal(m, b)
}
func (m *PublishBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishBlock.Marshal(b, m, deterministic)
}
func (dst *PublishBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishBlock.Merge(dst, src)
}
func (m *PublishBlock) XXX_Size() int {
	return xxx_messageInfo_PublishBlock.Size(m)
}
func (m *PublishBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishBlock.DiscardUnknown(m)
}

var xxx_messageInfo_PublishBlock proto.InternalMessageInfo

func (m *PublishBlock) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type ConfirmReq struct {
	Block                [][]byte `protobuf:"bytes,1,rep,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmReq) Reset()         { *m = ConfirmReq{} }
func (m *ConfirmReq) String() string { return proto.CompactTextString(m) }
func (*ConfirmReq) ProtoMessage()    {}
func (*ConfirmReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}
func (m *ConfirmReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmReq.Unmarshal(m, b)
}
func (m *ConfirmReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmReq.Marshal(b, m, deterministic)
}
func (dst *ConfirmReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmReq.Merge(dst, src)
}
func (m *ConfirmReq) XXX_Size() int {
	return xxx_messageInfo_ConfirmReq.Size(m)
}
func (m *ConfirmReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmReq proto.InternalMessageInfo

func (m *ConfirmReq) GetBlock() [][]byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type ConfirmAck struct {
	Account              []byte   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Sequence             uint32   `protobuf:"varint,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	Hash                 [][]byte `protobuf:"bytes,4,rep,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmAck) Reset()         { *m = ConfirmAck{} }
func (m *ConfirmAck) String() string { return proto.CompactTextString(m) }
func (*ConfirmAck) ProtoMessage()    {}
func (*ConfirmAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}
func (m *ConfirmAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmAck.Unmarshal(m, b)
}
func (m *ConfirmAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmAck.Marshal(b, m, deterministic)
}
func (dst *ConfirmAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmAck.Merge(dst, src)
}
func (m *ConfirmAck) XXX_Size() int {
	return xxx_messageInfo_ConfirmAck.Size(m)
}
func (m *ConfirmAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmAck.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmAck proto.InternalMessageInfo

func (m *ConfirmAck) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *ConfirmAck) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ConfirmAck) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ConfirmAck) GetHash() [][]byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type PovStatus struct {
	CurrentHeight        uint64   `protobuf:"varint,1,opt,name=CurrentHeight,proto3" json:"CurrentHeight,omitempty"`
	CurrentHash          []byte   `protobuf:"bytes,2,opt,name=CurrentHash,proto3" json:"CurrentHash,omitempty"`
	GenesisHash          []byte   `protobuf:"bytes,3,opt,name=GenesisHash,proto3" json:"GenesisHash,omitempty"`
	CurrentTD            []byte   `protobuf:"bytes,4,opt,name=CurrentTD,proto3" json:"CurrentTD,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PovStatus) Reset()         { *m = PovStatus{} }
func (m *PovStatus) String() string { return proto.CompactTextString(m) }
func (*PovStatus) ProtoMessage()    {}
func (*PovStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}
func (m *PovStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PovStatus.Unmarshal(m, b)
}
func (m *PovStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PovStatus.Marshal(b, m, deterministic)
}
func (dst *PovStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PovStatus.Merge(dst, src)
}
func (m *PovStatus) XXX_Size() int {
	return xxx_messageInfo_PovStatus.Size(m)
}
func (m *PovStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PovStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PovStatus proto.InternalMessageInfo

func (m *PovStatus) GetCurrentHeight() uint64 {
	if m != nil {
		return m.CurrentHeight
	}
	return 0
}

func (m *PovStatus) GetCurrentHash() []byte {
	if m != nil {
		return m.CurrentHash
	}
	return nil
}

func (m *PovStatus) GetGenesisHash() []byte {
	if m != nil {
		return m.GenesisHash
	}
	return nil
}

func (m *PovStatus) GetCurrentTD() []byte {
	if m != nil {
		return m.CurrentTD
	}
	return nil
}

func (m *PovStatus) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PovPublishBlock struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PovPublishBlock) Reset()         { *m = PovPublishBlock{} }
func (m *PovPublishBlock) String() string { return proto.CompactTextString(m) }
func (*PovPublishBlock) ProtoMessage()    {}
func (*PovPublishBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}
func (m *PovPublishBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PovPublishBlock.Unmarshal(m, b)
}
func (m *PovPublishBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PovPublishBlock.Marshal(b, m, deterministic)
}
func (dst *PovPublishBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PovPublishBlock.Merge(dst, src)
}
func (m *PovPublishBlock) XXX_Size() int {
	return xxx_messageInfo_PovPublishBlock.Size(m)
}
func (m *PovPublishBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_PovPublishBlock.DiscardUnknown(m)
}

var xxx_messageInfo_PovPublishBlock proto.InternalMessageInfo

func (m *PovPublishBlock) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type PovPullBlockReq struct {
	StartHash            []byte   `protobuf:"bytes,1,opt,name=StartHash,proto3" json:"StartHash,omitempty"`
	StartHeight          uint64   `protobuf:"varint,2,opt,name=StartHeight,proto3" json:"StartHeight,omitempty"`
	Count                uint32   `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	PullType             uint32   `protobuf:"varint,4,opt,name=PullType,proto3" json:"PullType,omitempty"`
	Reason               uint32   `protobuf:"varint,5,opt,name=Reason,proto3" json:"Reason,omitempty"`
	Locators             []byte   `protobuf:"bytes,6,opt,name=Locators,proto3" json:"Locators,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PovPullBlockReq) Reset()         { *m = PovPullBlockReq{} }
func (m *PovPullBlockReq) String() string { return proto.CompactTextString(m) }
func (*PovPullBlockReq) ProtoMessage()    {}
func (*PovPullBlockReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}
func (m *PovPullBlockReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PovPullBlockReq.Unmarshal(m, b)
}
func (m *PovPullBlockReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PovPullBlockReq.Marshal(b, m, deterministic)
}
func (dst *PovPullBlockReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PovPullBlockReq.Merge(dst, src)
}
func (m *PovPullBlockReq) XXX_Size() int {
	return xxx_messageInfo_PovPullBlockReq.Size(m)
}
func (m *PovPullBlockReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PovPullBlockReq.DiscardUnknown(m)
}

var xxx_messageInfo_PovPullBlockReq proto.InternalMessageInfo

func (m *PovPullBlockReq) GetStartHash() []byte {
	if m != nil {
		return m.StartHash
	}
	return nil
}

func (m *PovPullBlockReq) GetStartHeight() uint64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *PovPullBlockReq) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PovPullBlockReq) GetPullType() uint32 {
	if m != nil {
		return m.PullType
	}
	return 0
}

func (m *PovPullBlockReq) GetReason() uint32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

func (m *PovPullBlockReq) GetLocators() []byte {
	if m != nil {
		return m.Locators
	}
	return nil
}

type PovPullBlockRsp struct {
	Count                uint32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Block                []byte   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	Reason               uint32   `protobuf:"varint,3,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PovPullBlockRsp) Reset()         { *m = PovPullBlockRsp{} }
func (m *PovPullBlockRsp) String() string { return proto.CompactTextString(m) }
func (*PovPullBlockRsp) ProtoMessage()    {}
func (*PovPullBlockRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}
func (m *PovPullBlockRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PovPullBlockRsp.Unmarshal(m, b)
}
func (m *PovPullBlockRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PovPullBlockRsp.Marshal(b, m, deterministic)
}
func (dst *PovPullBlockRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PovPullBlockRsp.Merge(dst, src)
}
func (m *PovPullBlockRsp) XXX_Size() int {
	return xxx_messageInfo_PovPullBlockRsp.Size(m)
}
func (m *PovPullBlockRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PovPullBlockRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PovPullBlockRsp proto.InternalMessageInfo

func (m *PovPullBlockRsp) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PovPullBlockRsp) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *PovPullBlockRsp) GetReason() uint32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

type MessageAck struct {
	MessageHash          []byte   `protobuf:"bytes,1,opt,name=messageHash,proto3" json:"messageHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageAck) Reset()         { *m = MessageAck{} }
func (m *MessageAck) String() string { return proto.CompactTextString(m) }
func (*MessageAck) ProtoMessage()    {}
func (*MessageAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}
func (m *MessageAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageAck.Unmarshal(m, b)
}
func (m *MessageAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageAck.Marshal(b, m, deterministic)
}
func (dst *MessageAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageAck.Merge(dst, src)
}
func (m *MessageAck) XXX_Size() int {
	return xxx_messageInfo_MessageAck.Size(m)
}
func (m *MessageAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageAck.DiscardUnknown(m)
}

var xxx_messageInfo_MessageAck proto.InternalMessageInfo

func (m *MessageAck) GetMessageHash() []byte {
	if m != nil {
		return m.MessageHash
	}
	return nil
}

func init() {
	proto.RegisterType((*FrontierReq)(nil), "pb.FrontierReq")
	proto.RegisterType((*FrontierRsp)(nil), "pb.FrontierRsp")
	proto.RegisterType((*BulkPullReq)(nil), "pb.BulkPullReq")
	proto.RegisterType((*BulkPullRsp)(nil), "pb.BulkPullRsp")
	proto.RegisterType((*BulkPushBlock)(nil), "pb.BulkPushBlock")
	proto.RegisterType((*PublishBlock)(nil), "pb.PublishBlock")
	proto.RegisterType((*ConfirmReq)(nil), "pb.ConfirmReq")
	proto.RegisterType((*ConfirmAck)(nil), "pb.ConfirmAck")
	proto.RegisterType((*PovStatus)(nil), "pb.PovStatus")
	proto.RegisterType((*PovPublishBlock)(nil), "pb.PovPublishBlock")
	proto.RegisterType((*PovPullBlockReq)(nil), "pb.PovPullBlockReq")
	proto.RegisterType((*PovPullBlockRsp)(nil), "pb.PovPullBlockRsp")
	proto.RegisterType((*MessageAck)(nil), "pb.MessageAck")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5b, 0x8e, 0xd3, 0x30,
	0x14, 0x55, 0x1e, 0x2d, 0xf4, 0xa6, 0x11, 0xc8, 0x1a, 0x8d, 0x22, 0x34, 0x1f, 0x91, 0x35, 0x68,
	0x2a, 0x21, 0xcd, 0x0f, 0x2b, 0xe8, 0x94, 0xc7, 0x7c, 0x80, 0xa8, 0xdc, 0xb2, 0x80, 0x34, 0x35,
	0x6d, 0xd4, 0xd4, 0xce, 0xd8, 0xce, 0x48, 0xac, 0x82, 0xb5, 0xf0, 0xc5, 0xf6, 0x90, 0x1f, 0xa9,
	0x3d, 0x15, 0x08, 0xfe, 0x72, 0x8e, 0x8f, 0x7d, 0xcf, 0x3d, 0xbe, 0x31, 0xe4, 0x47, 0x2a, 0x65,
	0xb5, 0xa3, 0xb7, 0x9d, 0xe0, 0x8a, 0xa3, 0xb8, 0xdb, 0xe0, 0x2f, 0x90, 0x7d, 0x10, 0x9c, 0xa9,
	0x86, 0x0a, 0x42, 0x1f, 0x50, 0x01, 0xcf, 0xe6, 0xdb, 0xad, 0xa0, 0x52, 0x16, 0x51, 0x19, 0xcd,
	0xa6, 0x64, 0x80, 0xe8, 0x25, 0x24, 0xf3, 0x1d, 0x2d, 0xe2, 0x32, 0x9a, 0xe5, 0x44, 0x7f, 0xa2,
	0x0b, 0x18, 0x2d, 0x78, 0xcf, 0x54, 0x91, 0x18, 0xce, 0x02, 0xfc, 0x26, 0x38, 0x50, 0x76, 0xe8,
	0x0a, 0x26, 0x03, 0xd4, 0x47, 0x26, 0xb3, 0x29, 0xf1, 0x04, 0xfe, 0x11, 0x41, 0x76, 0xd7, 0xb7,
	0x87, 0x65, 0xdf, 0xb6, 0xba, 0xfc, 0x15, 0x4c, 0x56, 0xaa, 0x12, 0xea, 0xbe, 0x92, 0x7b, 0x67,
	0xc0, 0x13, 0xda, 0xdc, 0x7b, 0xb6, 0x35, 0x6b, 0xb1, 0x35, 0xe7, 0x20, 0x7a, 0x05, 0xcf, 0xf5,
	0x11, 0xeb, 0xef, 0x1d, 0x75, 0x6e, 0x4e, 0xd8, 0xdb, 0x4c, 0x03, 0x9b, 0xe8, 0x12, 0xc6, 0x7a,
	0x27, 0x95, 0xc5, 0xc8, 0x1c, 0xe5, 0x10, 0x7e, 0x1d, 0x18, 0x92, 0x9d, 0x96, 0x6d, 0x5a, 0x5e,
	0x1f, 0x86, 0x38, 0x1c, 0xc2, 0x37, 0x90, 0x5b, 0x99, 0xdc, 0xdf, 0x69, 0xe6, 0xaf, 0xc2, 0x6b,
	0x98, 0x2e, 0xfb, 0x4d, 0xdb, 0x0c, 0xba, 0x0b, 0x18, 0x99, 0x15, 0x27, 0xb3, 0x00, 0x63, 0x80,
	0x05, 0x67, 0xdf, 0x1a, 0x71, 0xd4, 0x29, 0x04, 0x9a, 0xc4, 0x6b, 0xd4, 0x49, 0x33, 0xaf, 0x0f,
	0xe6, 0xa2, 0xea, 0xda, 0xf4, 0x35, 0x5c, 0x94, 0x85, 0x26, 0xc3, 0x66, 0xc7, 0x2a, 0xd5, 0x0b,
	0xea, 0x72, 0xf2, 0x84, 0x4e, 0x6a, 0x45, 0x1f, 0x7a, 0xca, 0xea, 0x53, 0x52, 0x03, 0x46, 0x08,
	0x52, 0x13, 0x6e, 0x6a, 0xca, 0x9a, 0x6f, 0xfc, 0x33, 0x82, 0xc9, 0x92, 0x3f, 0xae, 0x54, 0xa5,
	0x7a, 0x89, 0xae, 0x21, 0x5f, 0xf4, 0x42, 0x50, 0xa6, 0xee, 0x69, 0xb3, 0xdb, 0xdb, 0xda, 0x29,
	0x79, 0x4a, 0xa2, 0x12, 0xb2, 0x81, 0xf0, 0x77, 0x15, 0x52, 0x5a, 0xf1, 0x91, 0x32, 0x2a, 0x1b,
	0x69, 0x14, 0x89, 0x55, 0x04, 0x94, 0xee, 0xc2, 0x6d, 0x58, 0xbf, 0x33, 0x37, 0x37, 0x25, 0x9e,
	0xd0, 0xab, 0xeb, 0xe6, 0x48, 0xa5, 0xaa, 0x8e, 0x9d, 0xb9, 0xc0, 0x84, 0x78, 0x02, 0xdf, 0xc0,
	0x8b, 0x25, 0x7f, 0xfc, 0x8f, 0xd8, 0x7f, 0x45, 0x4e, 0xd9, 0xb6, 0x46, 0xf6, 0xef, 0x11, 0x2c,
	0x21, 0xb3, 0xc0, 0xb6, 0x1f, 0x9b, 0xf6, 0x43, 0xea, 0xcf, 0x7f, 0xc5, 0x93, 0x01, 0x4d, 0xcf,
	0x06, 0xf4, 0x12, 0xc6, 0x84, 0x56, 0x92, 0x33, 0xd3, 0x49, 0x4e, 0x1c, 0xd2, 0x7b, 0x3e, 0xf1,
	0xba, 0x52, 0x5c, 0xc8, 0x62, 0x6c, 0x8c, 0x9c, 0x30, 0xfe, 0x7a, 0x66, 0x5c, 0x76, 0xba, 0xb0,
	0x9f, 0x87, 0x9c, 0x58, 0xe0, 0x1b, 0x8f, 0x83, 0xc6, 0x83, 0x92, 0x49, 0x58, 0x12, 0xdf, 0x02,
	0x7c, 0xb6, 0x4f, 0x84, 0x9e, 0xb1, 0x12, 0x32, 0xf7, 0x60, 0x04, 0x61, 0x84, 0xd4, 0x66, 0x6c,
	0x1e, 0x92, 0xb7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x09, 0x45, 0x92, 0xfd, 0x59, 0x04, 0x00,
	0x00,
}
