// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FrontierReq struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Age                  uint32   `protobuf:"varint,2,opt,name=Age,proto3" json:"Age,omitempty"`
	Count                uint32   `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrontierReq) Reset()         { *m = FrontierReq{} }
func (m *FrontierReq) String() string { return proto.CompactTextString(m) }
func (*FrontierReq) ProtoMessage()    {}
func (*FrontierReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *FrontierReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontierReq.Unmarshal(m, b)
}
func (m *FrontierReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontierReq.Marshal(b, m, deterministic)
}
func (dst *FrontierReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontierReq.Merge(dst, src)
}
func (m *FrontierReq) XXX_Size() int {
	return xxx_messageInfo_FrontierReq.Size(m)
}
func (m *FrontierReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontierReq.DiscardUnknown(m)
}

var xxx_messageInfo_FrontierReq proto.InternalMessageInfo

func (m *FrontierReq) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *FrontierReq) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *FrontierReq) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type FrontierRsp struct {
	TotalFrontierNum     uint32   `protobuf:"varint,1,opt,name=TotalFrontierNum,proto3" json:"TotalFrontierNum,omitempty"`
	HeaderBlock          []byte   `protobuf:"bytes,2,opt,name=HeaderBlock,proto3" json:"HeaderBlock,omitempty"`
	OpenBlock            []byte   `protobuf:"bytes,3,opt,name=OpenBlock,proto3" json:"OpenBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrontierRsp) Reset()         { *m = FrontierRsp{} }
func (m *FrontierRsp) String() string { return proto.CompactTextString(m) }
func (*FrontierRsp) ProtoMessage()    {}
func (*FrontierRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}
func (m *FrontierRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontierRsp.Unmarshal(m, b)
}
func (m *FrontierRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontierRsp.Marshal(b, m, deterministic)
}
func (dst *FrontierRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontierRsp.Merge(dst, src)
}
func (m *FrontierRsp) XXX_Size() int {
	return xxx_messageInfo_FrontierRsp.Size(m)
}
func (m *FrontierRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontierRsp.DiscardUnknown(m)
}

var xxx_messageInfo_FrontierRsp proto.InternalMessageInfo

func (m *FrontierRsp) GetTotalFrontierNum() uint32 {
	if m != nil {
		return m.TotalFrontierNum
	}
	return 0
}

func (m *FrontierRsp) GetHeaderBlock() []byte {
	if m != nil {
		return m.HeaderBlock
	}
	return nil
}

func (m *FrontierRsp) GetOpenBlock() []byte {
	if m != nil {
		return m.OpenBlock
	}
	return nil
}

type BulkPullReq struct {
	StartHash            []byte   `protobuf:"bytes,1,opt,name=StartHash,proto3" json:"StartHash,omitempty"`
	EndHash              []byte   `protobuf:"bytes,2,opt,name=EndHash,proto3" json:"EndHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkPullReq) Reset()         { *m = BulkPullReq{} }
func (m *BulkPullReq) String() string { return proto.CompactTextString(m) }
func (*BulkPullReq) ProtoMessage()    {}
func (*BulkPullReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}
func (m *BulkPullReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkPullReq.Unmarshal(m, b)
}
func (m *BulkPullReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkPullReq.Marshal(b, m, deterministic)
}
func (dst *BulkPullReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkPullReq.Merge(dst, src)
}
func (m *BulkPullReq) XXX_Size() int {
	return xxx_messageInfo_BulkPullReq.Size(m)
}
func (m *BulkPullReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkPullReq.DiscardUnknown(m)
}

var xxx_messageInfo_BulkPullReq proto.InternalMessageInfo

func (m *BulkPullReq) GetStartHash() []byte {
	if m != nil {
		return m.StartHash
	}
	return nil
}

func (m *BulkPullReq) GetEndHash() []byte {
	if m != nil {
		return m.EndHash
	}
	return nil
}

type BulkPullRsp struct {
	Blocktype            uint32   `protobuf:"varint,1,opt,name=blocktype,proto3" json:"blocktype,omitempty"`
	Block                []byte   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkPullRsp) Reset()         { *m = BulkPullRsp{} }
func (m *BulkPullRsp) String() string { return proto.CompactTextString(m) }
func (*BulkPullRsp) ProtoMessage()    {}
func (*BulkPullRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}
func (m *BulkPullRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkPullRsp.Unmarshal(m, b)
}
func (m *BulkPullRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkPullRsp.Marshal(b, m, deterministic)
}
func (dst *BulkPullRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkPullRsp.Merge(dst, src)
}
func (m *BulkPullRsp) XXX_Size() int {
	return xxx_messageInfo_BulkPullRsp.Size(m)
}
func (m *BulkPullRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkPullRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BulkPullRsp proto.InternalMessageInfo

func (m *BulkPullRsp) GetBlocktype() uint32 {
	if m != nil {
		return m.Blocktype
	}
	return 0
}

func (m *BulkPullRsp) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type BulkPushBlock struct {
	Blocktype            uint32   `protobuf:"varint,1,opt,name=blocktype,proto3" json:"blocktype,omitempty"`
	Block                []byte   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkPushBlock) Reset()         { *m = BulkPushBlock{} }
func (m *BulkPushBlock) String() string { return proto.CompactTextString(m) }
func (*BulkPushBlock) ProtoMessage()    {}
func (*BulkPushBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}
func (m *BulkPushBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkPushBlock.Unmarshal(m, b)
}
func (m *BulkPushBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkPushBlock.Marshal(b, m, deterministic)
}
func (dst *BulkPushBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkPushBlock.Merge(dst, src)
}
func (m *BulkPushBlock) XXX_Size() int {
	return xxx_messageInfo_BulkPushBlock.Size(m)
}
func (m *BulkPushBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkPushBlock.DiscardUnknown(m)
}

var xxx_messageInfo_BulkPushBlock proto.InternalMessageInfo

func (m *BulkPushBlock) GetBlocktype() uint32 {
	if m != nil {
		return m.Blocktype
	}
	return 0
}

func (m *BulkPushBlock) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type PublishBlock struct {
	Blocktype            uint32   `protobuf:"varint,1,opt,name=blocktype,proto3" json:"blocktype,omitempty"`
	Block                []byte   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishBlock) Reset()         { *m = PublishBlock{} }
func (m *PublishBlock) String() string { return proto.CompactTextString(m) }
func (*PublishBlock) ProtoMessage()    {}
func (*PublishBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}
func (m *PublishBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishBlock.Unmarshal(m, b)
}
func (m *PublishBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishBlock.Marshal(b, m, deterministic)
}
func (dst *PublishBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishBlock.Merge(dst, src)
}
func (m *PublishBlock) XXX_Size() int {
	return xxx_messageInfo_PublishBlock.Size(m)
}
func (m *PublishBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishBlock.DiscardUnknown(m)
}

var xxx_messageInfo_PublishBlock proto.InternalMessageInfo

func (m *PublishBlock) GetBlocktype() uint32 {
	if m != nil {
		return m.Blocktype
	}
	return 0
}

func (m *PublishBlock) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type ConfirmReq struct {
	Blocktype            uint32   `protobuf:"varint,1,opt,name=blocktype,proto3" json:"blocktype,omitempty"`
	Block                []byte   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmReq) Reset()         { *m = ConfirmReq{} }
func (m *ConfirmReq) String() string { return proto.CompactTextString(m) }
func (*ConfirmReq) ProtoMessage()    {}
func (*ConfirmReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}
func (m *ConfirmReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmReq.Unmarshal(m, b)
}
func (m *ConfirmReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmReq.Marshal(b, m, deterministic)
}
func (dst *ConfirmReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmReq.Merge(dst, src)
}
func (m *ConfirmReq) XXX_Size() int {
	return xxx_messageInfo_ConfirmReq.Size(m)
}
func (m *ConfirmReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmReq proto.InternalMessageInfo

func (m *ConfirmReq) GetBlocktype() uint32 {
	if m != nil {
		return m.Blocktype
	}
	return 0
}

func (m *ConfirmReq) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type ConfirmAck struct {
	Account              []byte   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Sequence             uint32   `protobuf:"varint,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	Blocktype            uint32   `protobuf:"varint,4,opt,name=blocktype,proto3" json:"blocktype,omitempty"`
	Block                []byte   `protobuf:"bytes,5,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmAck) Reset()         { *m = ConfirmAck{} }
func (m *ConfirmAck) String() string { return proto.CompactTextString(m) }
func (*ConfirmAck) ProtoMessage()    {}
func (*ConfirmAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}
func (m *ConfirmAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmAck.Unmarshal(m, b)
}
func (m *ConfirmAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmAck.Marshal(b, m, deterministic)
}
func (dst *ConfirmAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmAck.Merge(dst, src)
}
func (m *ConfirmAck) XXX_Size() int {
	return xxx_messageInfo_ConfirmAck.Size(m)
}
func (m *ConfirmAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmAck.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmAck proto.InternalMessageInfo

func (m *ConfirmAck) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *ConfirmAck) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ConfirmAck) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ConfirmAck) GetBlocktype() uint32 {
	if m != nil {
		return m.Blocktype
	}
	return 0
}

func (m *ConfirmAck) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func init() {
	proto.RegisterType((*FrontierReq)(nil), "pb.FrontierReq")
	proto.RegisterType((*FrontierRsp)(nil), "pb.FrontierRsp")
	proto.RegisterType((*BulkPullReq)(nil), "pb.BulkPullReq")
	proto.RegisterType((*BulkPullRsp)(nil), "pb.BulkPullRsp")
	proto.RegisterType((*BulkPushBlock)(nil), "pb.BulkPushBlock")
	proto.RegisterType((*PublishBlock)(nil), "pb.PublishBlock")
	proto.RegisterType((*ConfirmReq)(nil), "pb.ConfirmReq")
	proto.RegisterType((*ConfirmAck)(nil), "pb.ConfirmAck")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x53, 0x10, 0x95, 0x0b, 0x4d, 0xc8, 0xc4, 0x45, 0x63, 0x58, 0x90, 0xae, 0x88, 0x0b,
	0x37, 0xbe, 0x80, 0x85, 0x60, 0x58, 0x09, 0x29, 0xbe, 0x40, 0x7f, 0xae, 0xd0, 0x50, 0x66, 0x86,
	0xf9, 0x59, 0xf0, 0x1e, 0x3e, 0xb0, 0x99, 0x99, 0xfe, 0x19, 0xe3, 0x82, 0xb8, 0xeb, 0x39, 0x37,
	0xf9, 0xe6, 0xdc, 0xdb, 0x03, 0xfe, 0x09, 0xa5, 0x4c, 0xf6, 0xf8, 0xcc, 0x05, 0x53, 0x8c, 0xf4,
	0x78, 0x1a, 0x6e, 0x60, 0xf4, 0x26, 0x18, 0x55, 0x05, 0x8a, 0x18, 0xcf, 0x24, 0x80, 0xbb, 0x28,
	0xcf, 0x05, 0x4a, 0x19, 0x78, 0x33, 0x6f, 0x3e, 0x8e, 0x6b, 0x49, 0x26, 0xd0, 0x8f, 0xf6, 0x18,
	0xf4, 0x66, 0xde, 0xdc, 0x8f, 0xcd, 0x27, 0x79, 0x80, 0xc1, 0x92, 0x69, 0xaa, 0x82, 0xbe, 0xf5,
	0x9c, 0x08, 0x2f, 0x1d, 0xa0, 0xe4, 0xe4, 0x09, 0x26, 0x1f, 0x4c, 0x25, 0x65, 0xed, 0xbd, 0xeb,
	0x93, 0x25, 0xfb, 0xf1, 0x2f, 0x9f, 0xcc, 0x60, 0xb4, 0xc6, 0x24, 0x47, 0xb1, 0x28, 0x59, 0x76,
	0xb4, 0x4f, 0x8d, 0xe3, 0xae, 0x45, 0xa6, 0x30, 0xdc, 0x70, 0xa4, 0x6e, 0xde, 0xb7, 0xf3, 0xd6,
	0x08, 0x57, 0x30, 0x5a, 0xe8, 0xf2, 0xb8, 0xd5, 0x65, 0x69, 0x76, 0x99, 0xc2, 0x70, 0xa7, 0x12,
	0xa1, 0xd6, 0x89, 0x3c, 0x54, 0xdb, 0xb4, 0x86, 0xd9, 0x74, 0x45, 0x73, 0x3b, 0x73, 0x0f, 0xd5,
	0x32, 0x8c, 0x3a, 0x18, 0xc9, 0x0d, 0x26, 0x35, 0x78, 0x75, 0xe1, 0x58, 0x45, 0x6f, 0x0d, 0x73,
	0x84, 0xb4, 0x93, 0xd6, 0x89, 0x70, 0x09, 0xbe, 0x43, 0xc8, 0x43, 0x13, 0xfc, 0x6a, 0xc8, 0x02,
	0xc6, 0x5b, 0x9d, 0x96, 0xc5, 0x7f, 0x18, 0xaf, 0x00, 0x4b, 0x46, 0x3f, 0x0b, 0x71, 0xaa, 0x2e,
	0x72, 0x35, 0xe1, 0xcb, 0x6b, 0x10, 0x51, 0x76, 0xb4, 0x05, 0xc9, 0x32, 0xfb, 0xdb, 0xeb, 0x82,
	0x38, 0x69, 0xcf, 0x5d, 0xec, 0x69, 0xa2, 0xb4, 0xc0, 0x0a, 0xd1, 0x1a, 0xe4, 0x11, 0xee, 0x77,
	0x78, 0xd6, 0x48, 0x33, 0xac, 0xfa, 0xd2, 0xe8, 0x9f, 0xb1, 0x6e, 0xfe, 0x8c, 0x35, 0xe8, 0xc4,
	0x4a, 0x6f, 0x6d, 0x85, 0x5f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xca, 0xdd, 0x5d, 0x66, 0xd3,
	0x02, 0x00, 0x00,
}
