# Build gqlc in a stock Go builder container
FROM golang:1.17.3-alpine as builder

ARG BUILD_ACT=build

RUN apk add --no-cache make gcc musl-dev linux-headers git

COPY . /qlcchain/go-qlc

RUN \
    cd /qlcchain/go-qlc && go mod download && rm -rf /qlcchain

