# Build gqlc in a stock Go builder container
FROM golang:1.12.1-alpine as builder

ARG BUILD_ACT=build

RUN apk add --no-cache make gcc musl-dev linux-headers git

ADD . /qlcchain/go-qlc
RUN cd /qlcchain/go-qlc && make clean ${BUILD_ACT} && rm -rf /qlcchain
