
version: "3.5"

services:
  qlcchain_node:
    image: qlcchain/go-qlc:latest
    container_name: qlcchain_node
    command: ["--configParams=rpc.rpcEnabled=true", "--seed=B4F6494E3DD8A036EFF547C0293055B2A0644605DE4D9AC91B45343CD0E0E559"]
    ports:
      - "9734:9734"
      - "9735:9735"
      - "127.0.0.1:9736:9736"
    networks:
      - qlcchain
    volumes:
      - type: bind
        source: ./data/
        target: /qlcchain/.gqlcchain/
    restart: unless-stopped
 
networks:
  qlcchain:
    name: qlcchain

