// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protos

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StateBlock struct {
	Type                 []byte   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	PreviousHash         []byte   `protobuf:"bytes,3,opt,name=Previous,proto3" json:"Previous,omitempty"`
	Representative       []byte   `protobuf:"bytes,4,opt,name=Representative,proto3" json:"Representative,omitempty"`
	Balance              []byte   `protobuf:"bytes,5,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Link                 []byte   `protobuf:"bytes,6,opt,name=Link,proto3" json:"Link,omitempty"`
	Signature            []byte   `protobuf:"bytes,7,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Token                []byte   `protobuf:"bytes,8,opt,name=Token,proto3" json:"Token,omitempty"`
	Work                 []byte   `protobuf:"bytes,9,opt,name=Work,proto3" json:"Work,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateBlock) Reset()         { *m = StateBlock{} }
func (m *StateBlock) String() string { return proto.CompactTextString(m) }
func (*StateBlock) ProtoMessage()    {}
func (*StateBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *StateBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateBlock.Unmarshal(m, b)
}
func (m *StateBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateBlock.Marshal(b, m, deterministic)
}
func (m *StateBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateBlock.Merge(m, src)
}
func (m *StateBlock) XXX_Size() int {
	return xxx_messageInfo_StateBlock.Size(m)
}
func (m *StateBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_StateBlock.DiscardUnknown(m)
}

var xxx_messageInfo_StateBlock proto.InternalMessageInfo

func (m *StateBlock) GetType() []byte {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *StateBlock) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *StateBlock) GetPreviousHash() []byte {
	if m != nil {
		return m.PreviousHash
	}
	return nil
}

func (m *StateBlock) GetRepresentative() []byte {
	if m != nil {
		return m.Representative
	}
	return nil
}

func (m *StateBlock) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *StateBlock) GetLink() []byte {
	if m != nil {
		return m.Link
	}
	return nil
}

func (m *StateBlock) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *StateBlock) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *StateBlock) GetWork() []byte {
	if m != nil {
		return m.Work
	}
	return nil
}

type SmartContractBlock struct {
	Type                 []byte   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	PreviousHash         []byte   `protobuf:"bytes,3,opt,name=Previous,proto3" json:"Previous,omitempty"`
	Representative       []byte   `protobuf:"bytes,4,opt,name=Representative,proto3" json:"Representative,omitempty"`
	Balance              []byte   `protobuf:"bytes,5,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Link                 []byte   `protobuf:"bytes,6,opt,name=Link,proto3" json:"Link,omitempty"`
	Signature            []byte   `protobuf:"bytes,7,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Extra                []byte   `protobuf:"bytes,8,opt,name=Extra,proto3" json:"Extra,omitempty"`
	Work                 []byte   `protobuf:"bytes,9,opt,name=Work,proto3" json:"Work,omitempty"`
	Owner                []byte   `protobuf:"bytes,10,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Issuer               []byte   `protobuf:"bytes,11,opt,name=Issuer,proto3" json:"Issuer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartContractBlock) Reset()         { *m = SmartContractBlock{} }
func (m *SmartContractBlock) String() string { return proto.CompactTextString(m) }
func (*SmartContractBlock) ProtoMessage()    {}
func (*SmartContractBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *SmartContractBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartContractBlock.Unmarshal(m, b)
}
func (m *SmartContractBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartContractBlock.Marshal(b, m, deterministic)
}
func (m *SmartContractBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartContractBlock.Merge(m, src)
}
func (m *SmartContractBlock) XXX_Size() int {
	return xxx_messageInfo_SmartContractBlock.Size(m)
}
func (m *SmartContractBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartContractBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SmartContractBlock proto.InternalMessageInfo

func (m *SmartContractBlock) GetType() []byte {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *SmartContractBlock) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SmartContractBlock) GetPreviousHash() []byte {
	if m != nil {
		return m.PreviousHash
	}
	return nil
}

func (m *SmartContractBlock) GetRepresentative() []byte {
	if m != nil {
		return m.Representative
	}
	return nil
}

func (m *SmartContractBlock) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *SmartContractBlock) GetLink() []byte {
	if m != nil {
		return m.Link
	}
	return nil
}

func (m *SmartContractBlock) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SmartContractBlock) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *SmartContractBlock) GetWork() []byte {
	if m != nil {
		return m.Work
	}
	return nil
}

func (m *SmartContractBlock) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *SmartContractBlock) GetIssuer() []byte {
	if m != nil {
		return m.Issuer
	}
	return nil
}

func init() {
	proto.RegisterType((*StateBlock)(nil), "pb.StateBlock")
	proto.RegisterType((*SmartContractBlock)(nil), "pb.SmartContractBlock")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x92, 0xb1, 0x4a, 0x03, 0x41,
	0x10, 0x86, 0xc9, 0x99, 0x5c, 0xcc, 0x18, 0x2d, 0x16, 0x91, 0x29, 0x2c, 0xe4, 0x0a, 0xb1, 0xb2,
	0xf1, 0x09, 0x8c, 0x08, 0x0a, 0x82, 0x92, 0x0b, 0x58, 0x6f, 0x2e, 0x43, 0x3c, 0x2e, 0xd9, 0x3d,
	0x66, 0xe7, 0xa2, 0xbe, 0x96, 0xcf, 0x67, 0x21, 0x3b, 0x9b, 0x20, 0x8a, 0x4f, 0x60, 0x37, 0xdf,
	0xff, 0xff, 0xec, 0x0c, 0x3f, 0x0b, 0x87, 0x6b, 0x0a, 0xc1, 0x2e, 0xe9, 0xb2, 0x65, 0x2f, 0xde,
	0x64, 0xed, 0xbc, 0xf8, 0xec, 0x01, 0x94, 0x62, 0x85, 0x26, 0x2b, 0x5f, 0x35, 0xc6, 0x40, 0x7f,
	0xf6, 0xde, 0x12, 0xf6, 0xce, 0x7a, 0x17, 0xe3, 0xa9, 0xce, 0x06, 0x61, 0x78, 0xbd, 0x58, 0x30,
	0x85, 0x80, 0x99, 0xca, 0x3b, 0x34, 0x05, 0x8c, 0x9f, 0x98, 0x36, 0xb5, 0xef, 0xc2, 0x9d, 0x0d,
	0x2f, 0xb8, 0xa7, 0xf6, 0x0f, 0xcd, 0x9c, 0xc3, 0xd1, 0x94, 0x5a, 0xa6, 0x40, 0x4e, 0xac, 0xd4,
	0x1b, 0xc2, 0xbe, 0xa6, 0x7e, 0xa9, 0x71, 0xcb, 0xc4, 0xae, 0xac, 0xab, 0x08, 0x07, 0x69, 0xcb,
	0x16, 0xe3, 0x4d, 0x0f, 0xb5, 0x6b, 0x30, 0x4f, 0x37, 0xc5, 0xd9, 0x9c, 0xc2, 0xa8, 0xac, 0x97,
	0xce, 0x4a, 0xc7, 0x84, 0x43, 0x35, 0xbe, 0x05, 0x73, 0x0c, 0x83, 0x99, 0x6f, 0xc8, 0xe1, 0xbe,
	0x3a, 0x09, 0xe2, 0x3b, 0xcf, 0x9e, 0x1b, 0x1c, 0xa5, 0x77, 0xe2, 0x5c, 0x7c, 0x64, 0x60, 0xca,
	0xb5, 0x65, 0xb9, 0xf1, 0x4e, 0xd8, 0x56, 0xf2, 0xcf, 0x6a, 0xb8, 0x7d, 0x13, 0xb6, 0xbb, 0x1a,
	0x14, 0xfe, 0xaa, 0x21, 0x26, 0x1f, 0x5f, 0x1d, 0x31, 0x42, 0x4a, 0x2a, 0x98, 0x13, 0xc8, 0xef,
	0x43, 0xe8, 0x88, 0xf1, 0x40, 0xe5, 0x2d, 0xcd, 0x73, 0xfd, 0x3e, 0x57, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xed, 0xb9, 0x89, 0x8d, 0x4f, 0x02, 0x00, 0x00,
}
