name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-18.04
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          LABELS: "!wip,!work in progress"
          AUTOMERGE: "ready-to-merge"
          AUTOREBASE: "ready-to-rebase-and-merge"
          MERGE_METHOD: "squash"
          MERGE_FORKS: "false"