name: Build go-qlc builder
on: 
  schedule:
    - cron: "0 2 * * 0-6"

jobs:

  build:
    name: Publish qlc builder Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 10
    - 
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: qlcchain/go-qlc-builder
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile_builder