name: Release

on: 
  release:
    types: [published]

jobs:

  release:
    name: Release artifacts and docker images
    runs-on: ubuntu-18.04
 
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 10
      - name: Publish GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_CHGLOG_VERION: 0.9.1
        run: |
          wget -O /usr/bin/git-chglog https://github.com/git-chglog/git-chglog/releases/download/${GIT_CHGLOG_VERION}/git-chglog_linux_amd64
          chmod +x /usr/bin/git-chglog
          export TAG=${GITHUB_REF/refs\/tags\//}
          make VERSION=${TAG} release
      - name: Publish the Docker image to DockerHub
        uses: docker://goreng/publish-docker-github-action:v2.4
        with:
          name: qlcchain/go-qlc
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile
          buildargs: BUILD_ACT=build
      - name: Publish the Docker image to GitHub Packages
        uses: docker://goreng/publish-docker-github-action:v2.4
        with:
          name: docker.pkg.github.com/qlcchain/go-qlc/node-cli
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: docker/Dockerfile
          buildargs: BUILD_ACT=build