name: Release

on: 
  release:
    types: [published]

jobs:

  release:
    name: Release artifacts and docker images
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Publish GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          GIT_CHGLOG_VERSION: 0.14.1
        run: |
          GIT_CHGLOG_DOWNLOAD_FILE=git-chglog_linux_amd64.tar.gz
          GIT_CHGLOG_DOWNLOAD_URL=https://github.com/git-chglog/git-chglog/releases/download/v${GIT_CHGLOG_VERSION}/git-chglog_${GIT_CHGLOG_VERSION}_linux_amd64.tar.gz
          sudo wget -O ${GIT_CHGLOG_DOWNLOAD_FILE} ${GIT_CHGLOG_DOWNLOAD_URL}
          sudo tar -xzf $GIT_CHGLOG_DOWNLOAD_FILE -C /usr/local/bin git-chglog
          sudo chmod +x /usr/local/bin/git-chglog
          sudo rm $GIT_CHGLOG_DOWNLOAD_FILE
          export PATH=$PATH:/usr/local/bin
          export TAG=${GITHUB_REF/refs\/tags\//}
          make VERSION=${TAG} release
      - name: Publish mainnet Docker image to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@3.03
        with:
          name: qlcchain/go-qlc
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile
          buildargs: BUILD_ACT=build
          tag_names: true
      - name: Publish testnet Docker image to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@3.03
        with:
          name: qlcchain/go-qlc-test
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile
          buildargs: BUILD_ACT=build-test
          tag_names: true
      - name: Publish the Docker image to GitHub Packages
        uses: elgohr/Publish-Docker-Github-Action@3.03
        with:
          name: qlcchain/go-qlc/node-cli
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: docker/Dockerfile
          buildargs: BUILD_ACT=build
          tag_names: true